akun/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.index, name="index"),
]

fast/urls.py
from django.contrib import admin
from django.urls import path, include
from . import begin, views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path("", views.index, name='index'),
    path("home", views.home, name='home'),
    path("begin/", begin.begin, name='begin'),
    path('kelas/', include(('kelas.urls', 'kelas'), namespace='kelas')),
    path('modul/', include(('modul.urls', 'modul'), namespace='modul')),
    path('pesan/', include(('pesan.urls', 'pesan'), namespace='pesan')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

kelas/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.index, name="index"),
    path('jadwal', views.jadwal, name="jadwal"),
    path('upgrade', views.upgrade, name="upgrade"),
    path('confirm/<int:id>', views.confirm, name="confirm"),
    path('thank', views.thank, name="thank"),
    path('pertemuan', views.pertemuan, name="pertemuan"),
]

modul/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index.as_view(), name="index"),
    path('modul/<str:slug>', views.index.as_view(), name="koridor"),
    path('modul/subscribe/<str:slug>', views.index.as_view(), name="subscribe"),
]

kelas/models.py
from django.db import models
from django.contrib.auth.models import User as user_root
from config.models import Level
from akun.models import Users, Teacher

# Create your models here.
Language = [('EN', 'English'),('JP', 'Japan'),('SA', 'Arab'),('CN', 'China')]
jam     = [(0,'07:30'),(1,'09:00'),(2,'10:30'),(3,'13:00'),(4,'14:30'),(5,'16:00'),(6,'18:30'),(7,'20:00')]
jadwal = [(0, 'senin,  rabu, jum\'at'),(1, 'selasa,  kamis, sabtu'),(2, 'jum\'at,  sabtu, minggu')]

class Langganan(models.Model):
    durasi      = models.IntegerField(default=1)
    harga       = models.IntegerField(default=50000)
    diskon      = models.IntegerField(default=40000)
    def __str__(self):
        return "{} by {}".format(self.durasi, self.diskon)
    
class Program(models.Model):
    nama        = models.CharField(max_length=224,  unique=True)
    foto        = models.FileField(upload_to='photo/level', max_length=100, null=True, blank=True)
    keterangan  = models.CharField(max_length=224)
    nyawa       = models.IntegerField(default=0)
    biaya       = models.IntegerField(default=0)
    discount    = models.IntegerField(default=0)
    promo       = models.IntegerField(default=0)
    bestseller  = models.BooleanField(default=False)
    pertemuan   = models.IntegerField(default=0)
    siswa       = models.IntegerField(default=0)
    durasi      = models.IntegerField(default=1)
    mengulang   = models.BooleanField(default=False)
    ketentuan   = models.CharField(max_length=225, blank=True, null=True)
    materi      = models.CharField(max_length=225, blank=True, null=True)
    bonus       = models.CharField(max_length=225, blank=True, null=True)
    langganan   = models.ForeignKey(Langganan,blank=True, null=True,  on_delete=models.CASCADE, related_name="langganan")
    def __str__(self):
        return "{}".format(self.nama)
    
    def ketentuans(self):
        return self.ketentuan.split(",")
    def materis(self):
        return self.materi.split(",")
    def bonuses(self):
        return self.bonus.split(",")
    
class Kelas(models.Model):
    mentor      = models.ForeignKey(user_root,blank=True, null=True,on_delete=models.CASCADE,related_name="teacher_room")
    bahasa      = models.CharField(choices=Language, blank=True, max_length=3, default=1)
    program     = models.ForeignKey(Program,blank=True, null=True,on_delete=models.CASCADE, related_name="program_akun_room")
    level       = models.ForeignKey(Level,blank=True, null=True,on_delete=models.CASCADE, related_name="level_akun_room")
    time        = models.IntegerField(choices=jam, blank=True, default=1)
    mulai       = models.DateField(auto_now=False, auto_now_add=False, null=True, blank=True)
    jadwal      = models.IntegerField(choices=jadwal, blank=True, default=1)
    def __str__(self):
        return "{} {}".format(self.mentor, self.jadwal)
    def user(self):
        return Users.objects.get(user=self.mentor)
    def teacher(self):
        return Teacher.objects.get(user=self.mentor)
    def peserta(self):
        return UserMeeting.objects.filter(kelas=self).count()
        

class Schadule(models.Model):
    room        = models.ForeignKey(Kelas,blank=True, null=True,on_delete=models.CASCADE, related_name="teacher_schadule_room")
    mentor      = models.ForeignKey(user_root,blank=True, null=True,on_delete=models.CASCADE,related_name="mentor_schadule")
    terlaksana  = models.BooleanField(default=False)
    time        = models.IntegerField(choices=jam, blank=True, default=1)
    program     = models.ForeignKey(Program,blank=True, null=True,on_delete=models.CASCADE, related_name="level_akun_schadule")
    tanggal     = models.DateField(auto_now=False, auto_now_add=False, blank=True, null=True)
    def __str__(self):
        return "{} {}".format(self.room, self.tanggal)
    
class UserMeeting(models.Model):
    mentor      = models.ForeignKey(user_root, blank=True, null=True,on_delete=models.CASCADE, related_name="mentor_meeting")
    user        = models.ForeignKey(user_root, blank=True, null=True,on_delete=models.CASCADE, related_name="user_meeting")
    kelas       = models.ForeignKey(Kelas, blank=True, null=True,on_delete=models.CASCADE, related_name="user_meeting")
    program     = models.ForeignKey(Program, blank=True, null=True,on_delete=models.CASCADE, related_name="user_meeting")
    transaksi   = models.ForeignKey('transaksi.Transaksi', blank=True, null=True,on_delete=models.CASCADE, related_name="user_transaksi")
    start       = models.DateField(auto_now_add=True)
    end         = models.DateField(auto_now=False, auto_now_add=False, blank=True, null=True)
    meetremain  = models.IntegerField(default=0)
    def __str__(self):
        return "{}. {}-{}".format(self.id, self.user, self.meetremain)
    

#jika sudah di mentor langsung 
class UserMentor(models.Model):
    mentor      = models.ForeignKey(user_root,blank=True, null=True,on_delete=models.CASCADE,related_name="user_teacher")
    user        = models.ForeignKey(user_root,blank=True, null=True,on_delete=models.CASCADE,related_name="user_mentor")
    isMentored  = models.BooleanField(default=False)
    start       = models.DateField(auto_now=False, auto_now_add=False)
    end         = models.DateField(auto_now=False, auto_now_add=False)
    like        = models.IntegerField(blank=True, null=True)
    message     = models.CharField(max_length=224, blank=True)
    def __str__(self):
        return "{} - {}.{}".format(self.user, self.mentor, self.like)
    
#user yang mendaftar
class UserSchadule(models.Model):
    room        = models.ForeignKey(Kelas,blank=True, null=True,on_delete=models.CASCADE, related_name="room_room")
    schadule    = models.ForeignKey(Schadule,blank=True, null=True,on_delete=models.CASCADE, related_name="room_schadule")
    user        = models.ForeignKey(user_root,blank=True, null=True,on_delete=models.CASCADE,related_name="user_room")
    meeting     = models.ForeignKey(UserMeeting,blank=True, null=True,on_delete=models.CASCADE,related_name="user_meeting")
    hadir       = models.BooleanField(default=False)
    feedback    = models.CharField(max_length=225, blank=True, null=True)
    performance = models.IntegerField(blank=True, null=True)
    tanggal     = models.DateField(auto_now=False, auto_now_add=False, blank=True, null=True)
    def __str__(self):
        return "{} {}".format(self.room, self.tanggal)
    

templates/home/index.html
{% extends 'dashboard.html' %}
{% load custom_tags %}
{% load static %}

{% block title %}index{% endblock %}
{% block content %}
<div class="content">
  <div class="row">
    <div class="col-md-9">
      <div class="row">
        <div class="col-lg-3 col-md-6 col-6">
          <div class=" bg-white shadow p-2 m-1 rounded-3 w-100" style="height: 80px;">
            <h4>{% if me.premium %}Premium{% else %}FREE{% endif %}</h4>
            <a href="{% url 'kelas:upgrade' %}" class=" text-decoration-none text-primary d-flex justify-content-between w-100">Upgrade <i class="fa-solid fa-angle-right"></i></a>
          </div>
        </div>
        <div class="col-lg-3 col-md-6 col-6">
          <div class=" bg-white shadow p-2 m-1 rounded-3 w-100" style="height: 80px;">
            <h4>Level</h4>
            <div class="text-primary d-flex justify-content-between">{{me.level.name}} <i class="fa-solid fa-angle-right"></i></div>
          </div>
        </div>
        <div class="col-lg-3 col-md-6 col-6">
          <div class=" bg-white shadow p-2 m-1 rounded-3 w-100" style="height: 80px;">
            {% if mentor.mentor %}
            <div class="d-flex justify-content-between w-100">
              <div class="lh-1">
                <h4>Mentor</h4>
                <div style="line-height: 2px;">
                  <span class="text-muted text-uppercase h4">{{mentor.mentor.first_name}} {{mentor.mentor.last_name}}</span><br>
                  <div class="text-secondary fw-semibold ms-1">{{mentor.start|date:"d M"}} - {{mentor.end|date:"d M"}} </div>
                </div>
              </div>
              <a href="#" class="align-self-center h3 text-primary"><i class="fas fa-message"></i></a>
            </div>
            {% else %}
            <h4>Mentor</h4>
            <a href="{% url 'kelas:index' %}" class=" text-primary text-decoration-none d-flex justify-content-between w-100">Cari mentor <i class="fa-solid fa-angle-right"></i></a>
            {% endif %}
          </div>
        </div>
        <div class="col-lg-3 col-md-6 col-6">
          <div class=" bg-white shadow p-2 m-1 rounded-3 w-100" style="height: 80px;">
            <h4>Kelas</h4>
            {% if kelas %}
            {% else %}
            <a href="{% url 'modul:index' %}" class=" text-decoration-none text-primary d-flex justify-content-between w-100">Cari Kelas <i class="fa-solid fa-angle-right"></i></a>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
<div class="row">

      <!-- kelas -->
      <div class="container row" style="margin-top: 30px;">
        <div class="col-md-6 col-12">
          <div class="card sahdow-sm px-4">
            <h3 class="fw-bold my-3 ms-3">Pembelajaran</h3>
            {% for k in kelas %}
            <div class="d-flex flex-column">
              <div class="d-flex justify-content-between bg-light rounded-3 m-2 p-3">
                <div class="align-self-center w-100 me-3"><h5 class="fw-bold">Belajar {{k.kelas}}</h5>
                  <div class="progress" role="progressbar" aria-label="Example 1px high" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100" style="height: 5px">
                    <div class="progress-bar" style="width: {{k.percent}}%"></div>
                  </div>
                </div>
                <a href="{% url 'modul:koridor' slug=k.kelas.slug %}" class="btn text-primary fw-bold align-self-center">LANJUTKAN</a>
              </div>
            </div>
            {% endfor %}
            <div class="d-flex justify-content-end">
              <a href="{% url 'modul:index' %}" class="btn btn-primary rounded-0 m-2 fw-bold">Lihat Semua Kelas</a>
            </div>
          </div>
        </div>
        
        <div class="col-md-6 col-12">
          <div class="card shadow-sm px-4">
            <h3 class="fw-bold my-3 ms-3">Bootcamp</h3>
            <!-- hari ini -->
            {% if today %}
            <div class="d-flex flex-column">
              <div class="d-flex justify-content-between bg-light rounded-3 p-2">
                <div class="align-self-center w-100 me-3"><h5 class="fw-semibold">Hari ini</h5>
                  {{today.tanggal|date:"d M Y"}} | <span id="gettime">{{today.schadule.get_time_display}}</span> WIB
                </div>
                {% if today.now %}
                <a href="{{today.schadule.link}}" target="_blank" class="btn text-primary fw-bold align-self-center disabled" id="time">waiting</a>
                {% else %}
                <div></div>
                {% endif %}
              </div>
            </div>
            {% endif %}
            <!-- end hari ini -->
            
            <!-- besok -->
            {% if coming %}
            <div class="d-flex flex-column">
              <div class="d-flex justify-content-between bg-light rounded-3 p-2">
                <div class="align-self-center w-100 me-3"><h5 class="fw-semibold">Mendatang</h5>
                  {{coming.tanggal|date:"d M Y"}} | {{coming.room.get_time_display}} WIB
                </div>
                <a href="{% url 'kelas:index' %}" class="btn text-primary fw-bold align-self-center text-end">Selengkapnya</a>
              </div>
            </div>
            {% endif %}
            <!-- end besok -->
            
            <!-- terlewatkan -->
            {% if pass %}
            <div class="d-flex flex-column">
              <div class="d-flex justify-content-between bg-light rounded-3 p-2">
                <div class="align-self-center w-100 me-3"><h5 class="fw-semibold text-danger">Terlewatkan</h5>
                  {{pass.tanggal|date:"d M Y"}} | {{pass.room.get_time_display}} WIB
                </div>
                <a href="{% url 'kelas:index' %}" class="btn text-primary fw-bold align-self-center text-end">reschadule</a>
              </div>
            </div>
            {% endif %}
            <!-- end terlewatkan -->
            <div class="d-flex justify-content-end">
              <a href="{% url 'kelas:index' %}" class="btn btn-primary rounded-0 m-2 fw-bold">Selengkapnya</a>
            </div>
          </div>
        </div>
      </div>
    </div>
</div>

{% endblock content %}
{% block script %}
<script>
function perbarui(id){
  getid = document.getElementsByClassName("id_userroom");
  for(var i=0; i<getid.length;i++){
    getid[i].value = id;
  }
}
</script>
{% if today %}
<script>
var time              = document.getElementById("time");
var countdownElement  = document.getElementById("gettime");
function updateCountdown() {
    var now = new Date();

    var initialTime = countdownElement.innerText.split(":");
    var targetHours = parseInt(initialTime[0]);
    var targetMinutes = parseInt(initialTime[1]);
    var targetTime = new Date();
    targetTime.setHours(targetHours, targetMinutes-3, 0, 0);

    var timeDiff = targetTime - now;

    if (timeDiff <= 0) {
        time.innerHTML = 'Buka Zoom';
        time.classList.remove("disabled")
    } else {
        var hours = Math.floor(timeDiff / (1000 * 60 * 60));
        var minutes = Math.floor((timeDiff % (1000 * 60 * 60)) / (1000 * 60));
        var seconds = Math.floor((timeDiff % (1000 * 60)) / 1000);

        time.innerHTML = hours + 'h ' + minutes + 'm ' + seconds + 's';
    }
}
setInterval(updateCountdown, 1000);
</script>
{% endif %}
{% endblock script %}