akun/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.index, name="index"),
]

fast/urls.py
from django.contrib import admin
from django.urls import path, include
from . import begin, views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path("", views.index, name='index'),
    path("home", views.home, name='home'),
    path("begin/", begin.begin, name='begin'),
    path('kelas/', include(('kelas.urls', 'kelas'), namespace='kelas')),
    path('modul/', include(('modul.urls', 'modul'), namespace='modul')),
    path('pesan/', include(('pesan.urls', 'pesan'), namespace='pesan')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

kelas/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.index, name="index"),
    path('jadwal', views.jadwal, name="jadwal"),
    path('upgrade', views.upgrade, name="upgrade"),
    path('confirm/<int:id>', views.confirm, name="confirm"),
    path('thank', views.thank, name="thank"),
    path('pertemuan', views.pertemuan, name="pertemuan"),
]

templates/snippets/navbar.html
<nav id="navbar" class="navbar navbar-expand-lg bg-white fixed-top">
    <div class="container">
      <a class="navbar-brand" href="#home"><img src="../media/{{config.logo}}" style="width: 150px;" alt=""></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse text-center" id="navbarSupportedContent">
        <ul class="navbar-nav nav-pills gap-3 mx-auto mb-2 mb-lg-0 fw-semibold">
          <li class="nav-item">
            <a class="nav-link" href="#testimonial">Testimoni</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#tutor">Pengajar</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#kelas">Jadwal</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Pilihan Kelas
            </a>
            <ul class="dropdown-menu rounded-0">
              <li><a class="dropdown-item" href="#">Gratis</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{% url 'kelas:index' %}">Regular</a></li>
              <li><a class="dropdown-item" href="{% url 'kelas:index' %}">Semi Regular</a></li>
              <li><a class="dropdown-item" href="{% url 'kelas:index' %}">Private</a></li>
            </ul>
          </li>
        </ul>
        <form class="d-flex ms-2 gap-2 justify-content-center" role="search">
          {% if request.user.is_authenticated  %}
          <a href="{% url 'home' %}" class="btn btn-primary fw-bold px-3 ms-1">dashboard</a>
        <a href="{% url 'account_logout' %}" class="btn btn-outline-primary fw-bold px-3">Keluar</a>
          {% else %}
            <a href="{% url 'account_login' %}" class="btn btn-outline-primary fw-bold px-3">Login</a>
            <a href="{% url 'account_signup' %}" class="btn btn-primary text-white fw-bold px-3 ms-1">Daftar</a>
          {% endif %}
        </form>
      </div>
    </div>
</nav>

templates/snippets/sidebar.html
<div class="sidebar h6 shadow-sm" id="sidebar">
    <div class="d-none d-md-block"><img src="/media/{{config.icon}}" alt="logo" style="height: 60px;"></div>
    {% if peran == 'user' %}
    <a {% if url == 'index' %}class="active"{% endif %} href="{% url 'home' %}"><i class="fas fa-home me-3"></i> <span class="d-none d-sm-block">Home</span></a>
    <a {% if url == 'modul' %}class="active"{% endif %} href="{% url 'modul:index' %}"><i class="fa-solid fa-person-chalkboard me-3"></i><span class="d-none d-sm-block">Pelajaran</span></a>
    <a {% if url == 'kelas' %}class="active"{% endif %} href="{% url 'kelas:index' %}"><i class="fa-regular fa-calendar-check me-3"></i><span class="d-none d-sm-block">Kelas</span></a>
    <a href="#about"><i class="fa-solid fa-check me-3"></i><span class="d-none d-sm-block">About</span></a>
    {% endif %}
</div>

templates/snippets/topbar.html
{% load custom_tags %}
<div class="topbar bg-white text-primary shadow-sm" id="topbar">
    <div class="d-flex justify-content-between justify-content-md-start flex-md-row-reverse">
        <div class="d-flex flex-md-row-reverse">
          <div class="dropdown mx-2">
            <a class="btn btn-sm btn-outline-light dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <div class="rounded-img">
              <img src="/media/{% if user.photo %}{{ user.photo }}{% else %}/profile/image{% random_int 1 24 %}.jpg{% endif %}" alt="profile">
            </div>
            </a>
            <ul class="dropdown-menu py-3">
              {% if user.teacher %} <li><a class="dropdown-item h5 fw-light" href="{% url 'user:changeteacher' %}">Beralih ke mentor</a></li>{% endif %}
              {% if user.teacher %} <li><a class="dropdown-item h5 fw-light" href="{% url 'teacher:setting' %}">Teacher Setting</a></li>{% endif %}
              <li><a class="dropdown-item h5 fw-light" href="#">Profile</a></li>
              <li><a class="dropdown-item h5 fw-light" href="{% url 'kelas:upgrade' %}">Upgrade</a></li>
              <li><a class="dropdown-item h5 fw-light" href="{% url 'account_logout' %}">Logout</a></li>
            </ul>
          </div>
            <p class="p-4 h5 ">{% if user.user.first_name %}{{user.user.first_name}} {{user.user.last_name}}{% else %}ubah profile{% endif %} </p>
        </div>
        <div class="d-flex h4 text-primary me-4">
          <a href="{% url 'pesan:index' %}" class="align-self-center me-4"> <i class="fa-regular fa-message"></i></a>
          <a href="#" class=" align-self-center"><i class="fa-regular fa-bell"></i></a>
        </div>
    </div>
</div>