akun/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.index, name="index"),
]

fast/urls.py
from django.contrib import admin
from django.urls import path, include
from . import begin, views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path("", views.index, name='index'),
    path("home", views.home, name='home'),
    path("begin/", begin.begin, name='begin'),
    path('kelas/', include(('kelas.urls', 'kelas'), namespace='kelas')),
    path('modul/', include(('modul.urls', 'modul'), namespace='modul')),
    path('pesan/', include(('pesan.urls', 'pesan'), namespace='pesan')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

kelas/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.index, name="index"),
    path('jadwal', views.jadwal, name="jadwal"),
    path('upgrade', views.upgrade, name="upgrade"),
    path('confirm/<int:id>', views.confirm, name="confirm"),
    path('thank', views.thank, name="thank"),
    path('pertemuan', views.pertemuan, name="pertemuan"),
]

modul/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index.as_view(), name="index"),
    path('modul/<str:slug>', views.index.as_view(), name="koridor"),
    path('modul/subscribe/<str:slug>', views.index.as_view(), name="subscribe"),
]

modul/models/modul.py
from django.db import models
from django.contrib.auth.models import User as user_root
from ckeditor.fields import RichTextField
from config.models import Level, Kategori
from modul.models.user import Enroll

Language = [('EN', 'English'),('JP', 'Japan'),('SA', 'Arab'),('CN', 'China')]
# Create your models here.
class Module(models.Model):
    nama        = models.CharField(max_length=224)
    bahasa      = models.CharField(max_length=3,choices=Language, blank=True)
    slug        = models.SlugField(max_length=30, null=True)
    photo       = models.FileField(upload_to='module', max_length=100, default="module/default.jpg")
    kategori    = models.ForeignKey(Kategori,blank=True, null=True,on_delete=models.CASCADE, related_name="kategori_module")
    level       = models.ForeignKey(Level,blank=True, null=True,on_delete=models.CASCADE, related_name="level_module")
    keterangan  = models.CharField(blank=True,max_length=224)
    rangkuman   = RichTextField(blank=True, null=True)
    defaultget  = models.BooleanField(default=False)
    biaya       = models.IntegerField(default=0)
    discount    = models.IntegerField(default=0)
    premium     = models.BooleanField(default=False)
    mahkota     = models.IntegerField(default=0)
    dilihat     = models.IntegerField(default=0)
    certificate = models.BooleanField(default=False)
    rilis       = models.BooleanField(default=False)
    urutan      = models.IntegerField(blank=True, null=True)

    enroll      = Enroll.objects.all()
    def __str__(self):
        return " {}".format(self.nama)
    def subscribe(self):
        return self.enroll.filter(kelas=self, enroll=True).count()
    def pelajaran(self):
        return Pelajaran.objects.filter(module=self).count()
    def finish(self):
        return self.enroll.filter(kelas=self, finish=True).count()
    
# perubahan module yang ajukan oleh guru
class Update(models.Model):
    user        = models.ForeignKey(user_root,blank=True, null=True,on_delete=models.CASCADE, related_name="user_creator")
    module       = models.ForeignKey(Module,blank=True, null=True,on_delete=models.CASCADE, related_name="module_creator")
    perubahan   = models.CharField(max_length=225)
    approve     = models.BooleanField(default=False)
    date        = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return "{}-{}".format(self.user, self.module)
    
# bab pada lesson
class Bab(models.Model):
    module       = models.ForeignKey(Module,blank=True, null=True,on_delete=models.CASCADE, related_name="module_bab")
    bab         = models.CharField(max_length=50)
    urutan      = models.IntegerField(blank=True, null=True)
    rangkuman   = RichTextField(blank=True, null=True)
    premium     = models.BooleanField(default=False)
    def __str__(self):
        return "{}-{}".format(self.module, self.bab)
    

class Pelajaran(models.Model):
    module       = models.ForeignKey(Module,blank=True, null=True,on_delete=models.CASCADE, related_name="module_pelajaran")
    urutan      = models.IntegerField(blank=True, null=True)
    bab_module   = models.ForeignKey(Bab,blank=True, null=True,on_delete=models.CASCADE, related_name="bab_module")
    judul       = models.CharField(max_length=224)
    keterangan  = models.CharField(max_length=224, default="belum ada keterangan")
    vidio       = models.URLField(max_length=200, null=True, blank=True)
    text        = RichTextField()
    date        = models.DateField(auto_now_add=True, blank=True)
    approve     = models.BooleanField(default=False)
    def __str__(self):
        return "{}-{}".format(self.id, self.judul)


class Soal(models.Model):
    category    = models.ForeignKey(Kategori,blank=True, null=True,on_delete=models.CASCADE, related_name="quest_kategori")
    level       = models.ForeignKey(Level,blank=True, null=True,on_delete=models.CASCADE, related_name="quest_level")
    module       = models.ForeignKey(Module,blank=True, null=True,on_delete=models.CASCADE, related_name="quest_module")
    bab_module   = models.ForeignKey(Bab,blank=True, null=True,on_delete=models.CASCADE, related_name="bab_question")
    lesson      = models.ForeignKey(Pelajaran,blank=True, null=True,on_delete=models.CASCADE, related_name="quest_pelajaran")
    soal        = models.CharField(max_length=224)
    answer      = models.CharField(max_length=224)
    wrong1      = models.CharField(max_length=224)
    wrong2      = models.CharField(max_length=224)
    wrong3      = models.CharField(max_length=224)
    penjelasan  = models.TextField(default="Belum ada penjelasan")
    user        = models.ForeignKey(user_root,blank=True, null=True,on_delete=models.CASCADE, related_name="user_question")
    approve     = models.BooleanField(default=False)
    def __str__(self):
        return "{}.{}".format(self.soal, self.lesson)
    
class Games(models.Model):
    level       = models.IntegerField()
    soal        = models.CharField(max_length=224)
    answer      = models.CharField(max_length=224)
    dummy       = models.CharField(max_length=224)
    penjelasan  = models.TextField(default="Belum ada penjelasan")
    pelajaran   = models.ForeignKey(Pelajaran,blank=True, null=True,on_delete=models.CASCADE, related_name="games_pelajaran")
    module       = models.ForeignKey(Module,blank=True, null=True,on_delete=models.CASCADE, related_name="Games_module")
    bab_module   = models.ForeignKey(Bab,blank=True, null=True,on_delete=models.CASCADE, related_name="bab_games")
    user        = models.ForeignKey(user_root,blank=True, null=True,on_delete=models.CASCADE, related_name="user_games")
    approve     = models.BooleanField(default=False)
    def __str__(self):
        return "level {} - {}".format(self.level, self.soal)
    
class VocabGroup(models.Model):
    bahasa      = models.CharField(max_length=3,choices=Language, blank=True)
    origin      = models.CharField(max_length=50)
    translate   = models.CharField(max_length=50)
    level       = models.ForeignKey(Level,blank=True, null=True, on_delete=models.CASCADE, related_name="vocab_group_level")
    img         = models.FileField(upload_to='media/vocabgroup', max_length=100, default="media/vocabgroup/default.jpg")
    def __str__(self):
        return "{}.{}-{}".format(self.id, self.english, self.indo)

#penjabaran dari vocab grup seperti buah = anggur, jeruk dll
class Vocab(models.Model):
    vocabgroup  = models.ForeignKey(VocabGroup,blank=True, null=True, on_delete=models.CASCADE, related_name="vocab_group")
    origin      = models.CharField(max_length=50)
    translate   = models.CharField(max_length=50)
    success     = models.IntegerField(default=0)
    failed      = models.IntegerField(default=0)
    def __str__(self):
        return "{}.{}-{}".format(self.id, self.english, self.indo)

modul/models/user.py
from django.db import models
from django.contrib.auth.models import User as user_root
Language = [('EN', 'English'),('JP', 'Japan'),('SA', 'Arab'),('CN', 'China')]


class Enroll(models.Model):
    user        = models.ForeignKey(user_root, blank=True, null=True,on_delete=models.CASCADE, related_name="user_course_user")
    kelas       = models.ForeignKey("modul.Module",blank=True, null=True,on_delete=models.CASCADE, related_name="user_kelas")
    pelajaran   = models.ForeignKey("modul.Pelajaran",blank=True, null=True,on_delete=models.CASCADE, related_name="user_history_pelajaran") #mendapat histori pelajaran
    bab_kelas   = models.ForeignKey("modul.Bab",blank=True, null=True,on_delete=models.CASCADE, related_name="user_history")                  # mendapat histori bab
    tanggal     = models.DateField(auto_now_add=True)
    finish      = models.BooleanField(default=False)
    like        = models.IntegerField(default=0)
    feed        = models.CharField(blank=True, null=True, max_length=225)
    feedback    = models.CharField(blank=True, null=True, max_length=225)
    enroll      = models.BooleanField(default=False)
    def __str__(self):
        return "{} take {}".format(self.user, self.kelas)
    def lesson(self):
        return UserPelajaran.objects.filter(userCourse=self)
    def percent(self):
        lesson = UserPelajaran.objects.filter(userCourse=self)
        bab = UserBab.objects.filter(userCourse=self)
        return round(((lesson.filter(isdone=True).count()+bab.filter(isdone=True).count())/(lesson.count()+bab.count()))*100)

# lesson yang sudah dikerjakan
class UserPelajaran(models.Model):
    user        = models.ForeignKey(user_root, blank=True, null=True,on_delete=models.CASCADE, related_name="user_lesson_user")
    kelas       = models.ForeignKey("modul.Module",blank=True, null=True,on_delete=models.CASCADE, related_name="user_kelas_lesson")
    bab_kelas   = models.ForeignKey("modul.Bab",blank=True, null=True,on_delete=models.CASCADE, related_name="user_bab_kelas_lesson")
    pelajaran   = models.ForeignKey("modul.Pelajaran",blank=True, null=True,on_delete=models.CASCADE, related_name="user_pelajaran")
    userCourse  = models.ForeignKey(Enroll,blank=True, null=True,on_delete=models.CASCADE, related_name="usercourse_lesson")
    isdone      = models.BooleanField(default=False)
    question    = models.CharField(max_length=225, blank=True, null=True)
    answer      = models.CharField(max_length=225, blank=True, null=True)
    tgl         = models.DateField(auto_now_add=False, blank=True, null=True)
    def __str__(self):
        return "{} take {} by {}".format(self.id, self.user, self.pelajaran)
    
class UserBab(models.Model):
    user        = models.ForeignKey(user_root, blank=True, null=True,on_delete=models.CASCADE, related_name="user_bab_user")
    kelas       = models.ForeignKey("modul.Module",blank=True, null=True,on_delete=models.CASCADE, related_name="user_kelas_bab")
    bab_kelas   = models.ForeignKey("modul.Bab",blank=True, null=True,on_delete=models.CASCADE, related_name="userbab_bab")
    userCourse  = models.ForeignKey(Enroll,blank=True, null=True,on_delete=models.CASCADE, related_name="usercourse_bab")
    isdone      = models.BooleanField(default=False)
    tgl         = models.DateField(auto_now_add=False, blank=True, null=True)
    def __str__(self):
        return "{} take {} by {}".format(self.id, self.user, self.bab_kelas)


#vocab yang sudah di kerjakan
class UserVocab(models.Model):
    user        = models.ForeignKey(user_root, blank=True, null=True,on_delete=models.CASCADE, related_name="user_vocab_user")
    vocab       = models.ForeignKey("modul.VocabGroup", blank=True, null=True,on_delete=models.CASCADE, related_name="vocab")
    level       = models.IntegerField(default=0)
    benar       = models.IntegerField(default=0)
    salah       = models.IntegerField(default=0)
    isdone      = models.BooleanField(default=False)
    def __str__(self):
        return "{}-{}".format(self.user, self.vocab)
    
#games yang sudah di selesaikan
class UserGames(models.Model):
    user        = models.ForeignKey(user_root, blank=True, null=True,on_delete=models.CASCADE, related_name="user_games_user")
    games       = models.ForeignKey("modul.Games",blank=True, null=True,on_delete=models.CASCADE, related_name="Usergames_Games")
    kelas       = models.ForeignKey("modul.Module",blank=True, null=True,on_delete=models.CASCADE, related_name="Usergames_kelas")
    bab_kelas   = models.ForeignKey("modul.Bab",blank=True, null=True,on_delete=models.CASCADE, related_name="userbab_games")
    right       = models.IntegerField(default=0) #jumlah benar
    wrong       = models.IntegerField(default=0)  #jumlah salah
    failed      = models.IntegerField(default=0) #jumlah orang yg skip
    def __str__(self):
        return "{} {}{}".format(self.id, self.user, self.games)
    
class UserLatihan(models.Model):
    user        = models.ForeignKey(user_root, blank=True, null=True,on_delete=models.CASCADE, related_name="user_latihan_user")
    kelas       = models.ForeignKey("modul.Module",blank=True, null=True,on_delete=models.CASCADE, related_name="user_kelas_latihan")
    pelajaran   = models.ForeignKey("modul.Pelajaran",blank=True, null=True,on_delete=models.CASCADE, related_name="user_latihan_pelajaran")
    bab_kelas   = models.ForeignKey("modul.Bab",blank=True, null=True,on_delete=models.CASCADE, related_name="user_latihan")
    is_last     = models.BooleanField(default=False)
    is_finish   = models.BooleanField(default=False)
    nilai       = models.IntegerField(blank=True, null=True)
    tanggal     = models.DateTimeField(auto_now_add=True)
    countdown   = models.TimeField(default="00:10:00")
    countdownNow= models.TimeField(default="00:10:00")
    def __str__(self):
        return "{}{}".format(self.user, self.nilai)

    def soal(self):
        return UserQuestion.objects.filter(latihan=self)
    

class UserQuestion(models.Model):
    user        = models.ForeignKey(user_root, blank=True, null=True,on_delete=models.CASCADE, related_name="user_question_user")
    questions   = models.ForeignKey("modul.Soal",blank=True, null=True,on_delete=models.CASCADE, related_name="UserQuestion_Question")
    kelas       = models.ForeignKey("modul.Module",blank=True, null=True,on_delete=models.CASCADE, related_name="UserQuestion_kelas")
    bab_kelas   = models.ForeignKey("modul.Bab",blank=True, null=True,on_delete=models.CASCADE, related_name="userbab_Question")
    latihan     = models.ForeignKey(UserLatihan,blank=True, null=True,on_delete=models.CASCADE, related_name="user_latihan")
    selected    = models.CharField(max_length=225, blank=True, null=True)
    right       = models.BooleanField(default=False)
    tanggal     = models.DateField(auto_now_add=True)
    def __str__(self):
        return "{} {}{}".format(self.id, self.user, self.questions)
    

modul/views.py
from django.shortcuts import render, redirect
from django.views import View
from akun.models import Users
from modul.models.modul import Module, Pelajaran
from modul.models.user import Enroll, UserLatihan, UserPelajaran

context = {}
# Create your views here.
class index(View):
    def get(self, request, slug=None):
        if not slug:
            context["kelas"] = Module.objects.all()
            return render(request, 'modul/index.html', context)

        else:
            module = Module.objects.get(slug=slug)
            enroll = Enroll.objects.filter(user=request.user, kelas=module)
            lesson = UserPelajaran.objects.filter(user=request.user, kelas=module)
            if not enroll.exists():
                Enroll.objects.create(user=request.user, kelas=module)
                return redirect("modul:koridor", slug=slug)
            context["user"] = Users.objects.get(user=request.user)
            context["kelas"] = module
            context["enroll"] = enroll[0]
            context['history'] = enroll.first() if enroll.exists() else None
            context["pelajaran"] = str(lesson.filter(isdone=True).count()) + " / " + str(Pelajaran.objects.filter(module=module).count())
            context['latihan']      = UserLatihan.objects.filter(kelas=module, user=request.user)
            return render(request, 'modul/koridor.html', context)

def koridor(request, slug):
    pass

templates/modul/index.html
{% extends 'dashboard.html' %}
{% load static %}
{% block head %}
{% endblock head %}
{% block title %}Pelajaran{% endblock %}
{% block css %}
<style>
.images{
    position: relative;
}
.images > img {
    width: 80%;
}
.bottom-left {
  position: absolute;
  bottom: 10%;
  left:15%;
}
.text {
  white-space: nowrap; 
  width: 100%; 
  overflow: hidden;
  text-overflow: ellipsis;
}
.img-mobile {
    height: 250px;
    object-fit: cover;
}
@media (max-width: 576px) {
    .img-mobile {
        height: 120px;
    }
}
</style>
{% endblock css %}
{% block content %}
<div class="content">
    <p class="display-5 my-4">Proses Belajar</p>
    <div class="ms-1 row text-center">
        <a id="btnkelas" class="col-3 btn text-decoration-none fw-bold btn-primary rounded-0 py-2">Kelas</a>
        <a id="btnlangganan" class="col-3 btn text-decoration-none fw-bold btn-outline-primary  rounded-0 py-2 ">Kelas Tambahan</a>
    </div>
    <div class="mt-4" id="kls">
        <div class="row rounded-3">
        {% for k in kelas %}
        <div class="col-lg-4 col-6">
            <div class="card w-100">
                <img src="/media/{{k.photo}}" class="card-img-top w-100 img-mobile" alt="...">
                <div class="card-body d-flex flex-column  fw-semibold">
                    <h5 class="card-title">{{k.nama}} <span class="h6"><i class="far fa-star ms-3 me-1"></i>{% if k.ratting == None %}0.0{%else%}{{ k.ratting}}{% endif %}</span></h5>
                    {% if k.premium %}<div class="text-primary">Permium</div>{% else %} <div class="text-muted">Gratis</div> {% endif %}
                    <div class="card-text text-secondary">
                        <i class="far fa-user me-1"></i>{{k.subscribe}}
                        <i class="fas fa-book me-1 ms-2 "></i>{{k.pelajaran}}
                        <i class="fas fa-check ms-2 me-1"></i>{{k.finish}}
                    </div>
                </div>
                <a href="{% url 'modul:koridor' slug=k.slug %}" class="card-footer btn btn-primary bg-primary text-white fw-bold">
                    EXPLORE
                </a>
              </div>
        </div>
        {% endfor %}
        </div>
    </div>
    <div class="mt-4 d-none" id="langganan">
        <div class="bg-white shadow px-3 py-4 rounded-3">
        {% for k in langganan %}
            <div class="kelas d-flex justify-content-between p-2 bg-light">
                <div class="d-flex align-self-center fw-bold h4" style="min-width: 150px;">
                    <span class="col-1 text-secondary mx-4 align-self-center"><i class="fa-regular fa-circle"></i></span>
                    <div class="align-self-center mt-2">
                        <a href="{% url 'modul:koridor' slug=k.slug %}" class="d-md-none d-block  text-decoration-none text-muted">{{k.kelas}}{% if k.premium %} <span class="h6 text-primary pb-3"><i class="fa-solid fa-crown mx-3"></i></span> {% endif %}</a>
                        <span class="d-none d-md-block">{{k.kelas}} {% if k.premium %} <span class="h6 text-primary pb-3"><i class="fa-solid fa-crown mx-3"></i></span> {% endif %}</span>
                        <p class="h6 text-muted">
                            <i class="fas fa-star text-warning me-1"></i>{% if k.ratting == None %}0.0{%else%}{{ k.ratting}}{% endif %}
                            <i class="fas fa-book me-1 ms-2 text-primary"></i>{{k.pelajaran}}
                            <i class="fas fa-check ms-2 me-1"></i>{{k.finish}}
                        </p>
                    </div>
                </div>
                <div class=" align-self-center me-3 link d-none">
                    <a href="{% url 'modul:koridor' slug=k.slug %}" class="fw-bold btn btn-dark rounded-0">PELAJARI</a>
                </div>
            </div>
        {% endfor %}
        </div>
    </div>
{% endblock content %}
{% block script %}
<script>
    const kelas = document.getElementsByClassName("kelas");
    const link  = document.getElementsByClassName("link")
    const info  = document.getElementsByClassName("info")
    const klsbtn= document.getElementById("btnkelas")
    const langgananbtn= document.getElementById("btnlangganan")
    const kls= document.getElementById("kls")
    const langganan= document.getElementById("langganan")

    for(let i=0;i<kelas.length;i++){
        kelas[i].addEventListener("mouseenter", function(){
            link[i].classList.toggle("d-none")
            info[i].classList.toggle("d-none")
        })
        kelas[i].addEventListener("mouseleave", function(){
            link[i].classList.toggle("d-none")
            info[i].classList.toggle("d-none")
        })
    }
    klsbtn.addEventListener("click", function(){
        this.classList.remove("btn-outline-primary")
        this.classList.add("btn-primary")
        langgananbtn.classList.add("btn-outline-primary")
        langgananbtn.classList.remove("btn-primary")
        langganan.classList.toggle("d-none")
        kls.classList.toggle("d-none")
    })
    
    langgananbtn.addEventListener("click", function(){
        this.classList.remove("btn-outline-primary")
        this.classList.add("btn-primary")
        klsbtn.classList.add("btn-outline-primary")
        klsbtn.classList.remove("btn-primary")
        kls.classList.toggle("d-none")
        langganan.classList.toggle("d-none")
    })
</script>
{% endblock script %}

templates/modul/koridor.html
{% extends 'dashboard.html' %}
{% load static %}
{% block head %}
{% endblock head %}
{% block title %}Koridor{% endblock %}
{% block css %}
{% endblock css %}
{% block content %}
<div class="content">
    <div class="mt-2 mb-5">
        {% if not user.premium and kelas.premium %}
        <div class="shadow rounded-3 d-flex p-4 mb-5 bg-primary bg-opacity-25">
            <div class="display-4 m-4 align-self-center">
                <i class="fa-solid fa-triangle-exclamation"></i>
            </div>
            <div>
                <h3>Akun anda belum premium</h3>
                <h5>Langganan sekarang dan dapatkan experience nya</h5>
                <div>
                    <a href="{% url 'kelas:upgrade' %}" class="btn btn-primary rounded-0 px-5">Langganan sekarang</a>
                </div>
            </div>
        </div>
        {% endif %}
        <div class="d-flex justify-content-between">
            <div class="h2 fw-bold">Belajar {{kelas.kelas}}</div>
            <div class="d-flex gap-2">
                {% if enroll.finish and not enroll.like %} <button data-bs-toggle="modal" data-bs-target="#exampleModal" class="btn align-self-center btn-dark rounded-0 fw-semibold">Berikan Nilai</button>{% endif %}
                {% if enroll.enroll and enroll.finish %} <a href="#" class="btn align-self-center btn-dark rounded-0 fw-semibold {% if not enroll.like and not enroll.feed %}disabled{% endif %}">Cetak Sertifikat</a> {% endif %}
                {% if enroll.enroll %}
                <a href="{% url 'modul:pelajaran' slug=kelas.slug urutan_bab=history.bab_kelas.urutan urutan_pelajaran=history.pelajaran.urutan  %}" class="text-uppercase btn align-self-center btn-dark rounded-0 fw-semibold">Pelajari</a>
                {% else %}
                <form action="{% url 'modul:subscribe' slug=kelas.slug %}" method="post">{% csrf_token %} <input {% if not user.premium and kelas.premium %}disabled{%endif%} type="submit" value="Daftar" name="daftar" class="btn btn-lg fw-semibold btn-dark rounded-0 shadow"></form>
                {% endif %}
            </div>
        </div>
        <div class="bg-white shadow-sm p-3 my-4 rounded-2 card">
            <div class=" h3 fw-bold">{{pelajaran}} sudah dipelajari</div>
            <div class="d-flex justify-content-between ">
                <div class="fw-semibold text-muted h5 align-self-center">{{kelas.bab}} topik, {{kelas.pelajaran}} pelajaran</div>
                <p class="align-self-center text-muted me-4 mt-3">
                    <i class="fas fa-eye ms-1 me-1"></i>{{kelas.see}}
                    <i class="fas fa-user ms-2 me-1"></i>{{kelas.subscribe}}
                    <i class="fas fa-check ms-2 me-1"></i>{{kelas.finish}}
                    <i class="fas fa-message ms-2 me-1"></i>{{kelas.feedback}}
                    <i class="fas fa-star text-warning me-1 ms-3"></i>{% if kelas.ratting == None %}0.0{%else%}{{ kelas.ratting}}{% endif %}
                </p>
            </div>
        </div>
        <div class="shadow-sm my-4 rounded-2 card">
            <div class="card-header fw-bold h3"><i class="fa-solid fa-book text-primary me-3"></i>Riwayat Soal</div>
            <div class="p-3">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">No</th>
                            <th scope="col">Topik</th>
                            <th scope="col">Tanggal</th>
                            <th scope="col">Nilai</th>
                            <th scope="col">Lihat</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for latih in latihan %}
                        <tr>
                            <td>{{forloop.counter}}</td>
                            <th scope="row">{% if latih.bab_kelas %}{{latih.bab_kelas}}{% else %}Ujian{% endif %}</th>
                            <td>{{latih.tanggal|date:"d/m/Y"}}</td>
                            <td class="text-{% if latih.nilai >= 80 %}success{% else %}danger{% endif %} fw-bold">{{latih.nilai}}</td>
                            <td><a href="{% url 'user:pembahasan' id=latih.id %}" class="btn btn-outline-dark rounded-0 btn-sm">Detail</a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        
        <div class="shadow-sm my-4 rounded-2 card">
            <div class="card-header fw-bold h3"><i class="fa-solid fa-people-group text-info me-3"></i>Forum</div>
            <div class="p-3">
                <div class="d-flex h4 fw-bold mb-4"><div class="col-8">Apa kata mereka ?</div><div class="col-4 text-center">Kategori</div></div>
                <div class="d-flex fw-bold mb-2"><div class="col-8">Susah nagengr </div><div class="col-4 text-center align-self-center ">Pengenalan</div></div>
                <div class="d-flex fw-bold mb-2"><div class="col-8">di isi apa yah</div><div class="col-4 text-center align-self-center ">Pengenalan 2</div></div>
                <div class="d-flex fw-bold mb-2"><div class="col-8">gak tau</div><div class="col-4 text-center align-self-center">Pengenalan 3</div></div>
            </div>
        </div>
        
        <div class="shadow-sm my-4 rounded-2 card">
            <div class="card-header fw-bold h3"><i class="fas fa-star text-warning me-3"></i> Ratting</div>
            <div class="p-3">
                <div class="d-flex h4 fw-bold mb-4"><div class="col-8">Feedback</div><div class="col-4 text-center">Ratting</div></div>
                <div class="d-flex fw-bold mb-2"><div class="col-8">Susah nagengr </div><div class="col-4 text-center align-self-center ">5/5</div></div>
                <div class="d-flex fw-bold mb-2"><div class="col-8">di isi apa yah</div><div class="col-4 text-center align-self-center ">2/5</div></div>
                <div class="d-flex fw-bold mb-2"><div class="col-8">gak tau</div><div class="col-4 text-center align-self-center">3/5</div></div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block modal %}
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          ...
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary">Save changes</button>
        </div>
      </div>
    </div>
  </div>
{% endblock modal %}
{% block script %}
{% endblock script %}