akun/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.index, name="index"),
]

fast/urls.py
from django.contrib import admin
from django.urls import path, include
from . import begin, views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path("", views.index, name='index'),
    path("home", views.home, name='home'),
    path("begin/", begin.begin, name='begin'),
    path('kelas/', include(('kelas.urls', 'kelas'), namespace='kelas')),
    path('modul/', include(('modul.urls', 'modul'), namespace='modul')),
    path('pesan/', include(('pesan.urls', 'pesan'), namespace='pesan')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

kelas/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.index, name="index"),
    path('jadwal', views.jadwal, name="jadwal"),
    path('upgrade', views.upgrade, name="upgrade"),
    path('confirm/<int:id>', views.confirm, name="confirm"),
    path('thank', views.thank, name="thank"),
    path('pertemuan', views.pertemuan, name="pertemuan"),
]

kelas/models.py
from django.db import models
from django.contrib.auth.models import User as user_root
from config.models import Level
from akun.models import Users, Teacher

# Create your models here.
Language = [('EN', 'English'),('JP', 'Japan'),('SA', 'Arab'),('CN', 'China')]
jam     = [(0,'07:30'),(1,'09:00'),(2,'10:30'),(3,'13:00'),(4,'14:30'),(5,'16:00'),(6,'18:30'),(7,'20:00')]
jadwal = [(0, 'senin,  rabu, jum\'at'),(1, 'selasa,  kamis, sabtu'),(2, 'jum\'at,  sabtu, minggu')]

class Langganan(models.Model):
    durasi      = models.IntegerField(default=1)
    harga       = models.IntegerField(default=50000)
    diskon      = models.IntegerField(default=40000)
    def __str__(self):
        return "{} by {}".format(self.durasi, self.diskon)
    
class Program(models.Model):
    nama        = models.CharField(max_length=224,  unique=True)
    foto        = models.FileField(upload_to='photo/level', max_length=100, null=True, blank=True)
    keterangan  = models.CharField(max_length=224)
    nyawa       = models.IntegerField(default=0)
    biaya       = models.IntegerField(default=0)
    discount    = models.IntegerField(default=0)
    promo       = models.IntegerField(default=0)
    bestseller  = models.BooleanField(default=False)
    pertemuan   = models.IntegerField(default=0)
    siswa       = models.IntegerField(default=0)
    durasi      = models.IntegerField(default=1)
    mengulang   = models.BooleanField(default=False)
    ketentuan   = models.CharField(max_length=225, blank=True, null=True)
    materi      = models.CharField(max_length=225, blank=True, null=True)
    bonus       = models.CharField(max_length=225, blank=True, null=True)
    langganan   = models.ForeignKey(Langganan,blank=True, null=True,  on_delete=models.CASCADE, related_name="langganan")
    def __str__(self):
        return "{}".format(self.nama)
    
    def ketentuans(self):
        return self.ketentuan.split(",")
    def materis(self):
        return self.materi.split(",")
    def bonuses(self):
        return self.bonus.split(",")
    
class Kelas(models.Model):
    mentor      = models.ForeignKey(user_root,blank=True, null=True,on_delete=models.CASCADE,related_name="teacher_room")
    bahasa      = models.CharField(choices=Language, blank=True, max_length=3, default=1)
    program     = models.ForeignKey(Program,blank=True, null=True,on_delete=models.CASCADE, related_name="program_akun_room")
    level       = models.ForeignKey(Level,blank=True, null=True,on_delete=models.CASCADE, related_name="level_akun_room")
    time        = models.IntegerField(choices=jam, blank=True, default=1)
    mulai       = models.DateField(auto_now=False, auto_now_add=False, null=True, blank=True)
    jadwal      = models.IntegerField(choices=jadwal, blank=True, default=1)
    def __str__(self):
        return "{} {}".format(self.mentor, self.jadwal)
    def user(self):
        return Users.objects.get(user=self.mentor)
    def teacher(self):
        return Teacher.objects.get(user=self.mentor)
    def peserta(self):
        return UserMeeting.objects.filter(kelas=self).count()
        

class Schadule(models.Model):
    room        = models.ForeignKey(Kelas,blank=True, null=True,on_delete=models.CASCADE, related_name="teacher_schadule_room")
    mentor      = models.ForeignKey(user_root,blank=True, null=True,on_delete=models.CASCADE,related_name="mentor_schadule")
    terlaksana  = models.BooleanField(default=False)
    time        = models.IntegerField(choices=jam, blank=True, default=1)
    program     = models.ForeignKey(Program,blank=True, null=True,on_delete=models.CASCADE, related_name="level_akun_schadule")
    tanggal     = models.DateField(auto_now=False, auto_now_add=False, blank=True, null=True)
    def __str__(self):
        return "{} {}".format(self.room, self.tanggal)
    
class UserMeeting(models.Model):
    mentor      = models.ForeignKey(user_root, blank=True, null=True,on_delete=models.CASCADE, related_name="mentor_meeting")
    user        = models.ForeignKey(user_root, blank=True, null=True,on_delete=models.CASCADE, related_name="user_meeting")
    kelas       = models.ForeignKey(Kelas, blank=True, null=True,on_delete=models.CASCADE, related_name="user_meeting")
    program     = models.ForeignKey(Program, blank=True, null=True,on_delete=models.CASCADE, related_name="user_meeting")
    transaksi   = models.ForeignKey('transaksi.Transaksi', blank=True, null=True,on_delete=models.CASCADE, related_name="user_transaksi")
    start       = models.DateField(auto_now_add=True)
    end         = models.DateField(auto_now=False, auto_now_add=False, blank=True, null=True)
    meetremain  = models.IntegerField(default=0)
    def __str__(self):
        return "{}. {}-{}".format(self.id, self.user, self.meetremain)
    

#jika sudah di mentor langsung 
class UserMentor(models.Model):
    mentor      = models.ForeignKey(user_root,blank=True, null=True,on_delete=models.CASCADE,related_name="user_teacher")
    user        = models.ForeignKey(user_root,blank=True, null=True,on_delete=models.CASCADE,related_name="user_mentor")
    isMentored  = models.BooleanField(default=False)
    start       = models.DateField(auto_now=False, auto_now_add=False)
    end         = models.DateField(auto_now=False, auto_now_add=False)
    like        = models.IntegerField(blank=True, null=True)
    message     = models.CharField(max_length=224, blank=True)
    def __str__(self):
        return "{} - {}.{}".format(self.user, self.mentor, self.like)
    
#user yang mendaftar
class UserSchadule(models.Model):
    room        = models.ForeignKey(Kelas,blank=True, null=True,on_delete=models.CASCADE, related_name="room_room")
    schadule    = models.ForeignKey(Schadule,blank=True, null=True,on_delete=models.CASCADE, related_name="room_schadule")
    user        = models.ForeignKey(user_root,blank=True, null=True,on_delete=models.CASCADE,related_name="user_room")
    meeting     = models.ForeignKey(UserMeeting,blank=True, null=True,on_delete=models.CASCADE,related_name="user_meeting")
    hadir       = models.BooleanField(default=False)
    feedback    = models.CharField(max_length=225, blank=True, null=True)
    performance = models.IntegerField(blank=True, null=True)
    tanggal     = models.DateField(auto_now=False, auto_now_add=False, blank=True, null=True)
    def __str__(self):
        return "{} {}".format(self.room, self.tanggal)
    

kelas/views.py
from django.shortcuts import render, redirect
from akun.models import Users
from kelas.models import Program, UserMeeting, UserSchadule, Kelas, UserMentor, Schadule
from transaksi.models import Transaksi

from kelas.utils import upgradeKelas, confirmUpgrade
from transaksi.utils import status
from django.contrib import messages

import datetime
x = datetime.datetime.now()

context = {}
# Create your views here.
def index(request):
    transaksi               = Transaksi.objects.filter(user=request.user, terbayar=True)
    meeting                 = UserMeeting.objects.filter(transaksi=transaksi.filter(terpakai=True).first(), mentor__isnull=False)
    room                    = UserSchadule.objects.filter(user=request.user)
    if not transaksi.exists():
        return redirect("kelas:upgrade")
    if not transaksi.filter(terpakai=True).exists():
        return redirect("kelas:jadwal")
    
    if request.method == 'POST':
        sch =  Schadule.objects.filter(program=meeting.first().program, time=request.POST["time"], tanggal=request.POST["date"]).order_by("?")
        if sch.exists():
            sch_first = sch.first()
            room.filter(id=request.POST['id']).update(schadule=sch_first, room=sch_first.room, tanggal=sch_first.tanggal)
            messages.success(request, 'Anda akan belajar dengan {} pada tangal {} jam {}'.format(sch_first.mentor.first_name+" "+sch_first.mentor.last_name, sch_first.tanggal, sch_first.get_time_display()))
            return redirect("kelas:index")
        else:
            messages.error(request, 'Kelas tidak ditemukan, coba ganti tanggal lain atau jam lain')
            return redirect("kelas:index")
        
    context["user"]         = Users.objects.get(user=request.user)
    context['yet']          = room.filter(hadir=False, tanggal__gte=x).order_by("tanggal")[:5]
    context['done']         = room.filter(tanggal__lt=x)[:5]
    context['meeting']      = meeting.first()
    return render(request, "kelas/index.html", context)

def upgrade(request):
    context["user"]     = Users.objects.get(user=request.user)
    context['paket'] = Program.objects.all().order_by("biaya")
    return render(request, "kelas/upgrade.html", context)

def confirm(request,id):
    url = upgradeKelas(request, id)
    return redirect(url)

def thank(request):
    id = request.GET.get('order_id')
    trans = status(id)
    if request.GET.get('transaction_status') == "settlement":
        transaksi = Transaksi.objects.get(id=id)
        confirmUpgrade(request, transaksi)
        transaksi.terbayar = True
        transaksi.save()
        return render(request, "kelas/thank.html", context={})
    else:
        UserMeeting.objects.filter(SessionID=trans["Data"]["SessionId"]).delete()
        return redirect('kelas:upgrade')
    
def jadwal(request):
    transaksi                 = Transaksi.objects.filter(user=request.user, terbayar=True, terpakai=False).first()
    meeting = UserMeeting.objects.get(user=request.user, transaksi=transaksi)
    if request.method == 'POST':
        kelas    = Kelas.objects.get(id=request.POST["id"])
        transaksi.terpakai = True
        transaksi.save()
        meeting.kelas    = kelas
        meeting.mentor  = kelas.mentor
        meeting.save()
        UserMentor.objects.create(mentor=kelas.mentor, user=request.user, isMentored=True, start=kelas.mulai, end=(kelas.mulai + datetime.timedelta(days=90)))
        for i in Schadule.objects.filter(room=kelas):
            UserSchadule.objects.create(room=kelas, schadule=i, user=request.user,meeting=meeting, tanggal = i.tanggal)
        return redirect("kelas:index")

    context["user"]         = Users.objects.get(user=request.user)
    context['mentor']       = Kelas.objects.filter(program=transaksi.program)
    context['meeting']      = UserMeeting.objects.get(user=request.user, transaksi=transaksi)
    return render(request, "kelas/jadwal.html", context)

def pertemuan(request):
    context["user"]         = Users.objects.get(user=request.user)
    context['jadwal']       = UserSchadule.objects.filter(user=request.user).order_by("tanggal")
    return render(request, "kelas/pertemuan.html", context)

templates/kelas/index.html
{% extends 'dashboard.html' %}
{% load static %}
{% block head %}
{% endblock head %}
{% block title %}dashboard{% endblock %}
{% block css %}
<style>
  .btn-rsch > a {
    display: none;
  }
  .btn-rsch:hover > a {
    display: block;
  }
  .messages {
    width: 100%;
    display: flex;
    border-radius: 2%;
    padding: 20px;
  }
  .messages.messages-error{
    background-color: yellow
  }
  .messages.messages-success  {
    background-color: lightgreen;
  }

  @media screen and (max-width: 576px) {
  .btn-rsch > a {
    display: block;
  }
  }
</style>
{% endblock css %}
{% block content %}
<div class="content">
  {% if messages %}
      {% for message in messages %}
        <div class="messages {% if message.tags %}messages-{{ message.tags }} mb-4"{% endif %}>
          <h3>{{ message }}</h3>
        </div>
      {% endfor %}
  {% endif %}
  <div class="bg-white rounded shadow-sm">
    <div class="container p-3">
      <div class="row">
        <div class="col-6 col-md-3">
          <div class="display-6">Level</div>
          <div class="h4 fw-light">{{user.level.name}}<i class="ms-1 fa-regular fa-thumbs-up"></i></div>
        </div>
        <div class="col-6 col-md-3">
          <div class="display-6">Performa</div>
          <div class="h4 fw-light">30%</div>
        </div>
        <div class="col-6 col-md-3">
          <div class="display-6">Pertemuan</div>
          <div class="h5 fw-semibold">{{meeting.meetremains}} <span class="fw-lighter">dari</span> {{meeting.accountlevel.meeting}} Pertemuan</div>
        </div>
        <div class="col-6 col-md-3">
          <div class="display-6">Berakhir</div>
          <div class="h4 fw-light">{{meeting.end|date:"d M Y"}}</div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 col-lg-6 mt-4">
      <div class="container shadow-sm rounded bg-white p-3" style="height: 450px;">
        <p class="h3 fw-semibold my-2">Akan datang</p>
        <table class="table  table-hover">
          <thead>
            <tr>
              <th scope="col">TUTOR</th>
              <th scope="col">Tanggal</th>
              <th scope="col">Jadwal</th>
              <th scope="col" style="width: 120px;"></th>
            </tr>
          </thead>
          <tbody>
            {% for y in yet %}
            <tr style="height: 50px;">
              <td class="d-none">{{y.id}}</td>
              <th><div class="rounded-img" style="width: 30px; height: 30px;"><img src="/media/{{y.room.usermentor.photo}}" alt=""></div></th>
              <td>{{y.tanggal|date:"d M Y"}}</td>
              <td><span {% if y.now %} id="gettime" {% endif %}>{{y.schadule.get_time_display}}</span> WIB</td>
                {% if y.now %}
                <td class="text-end"><a href="{{y.room.link}}" target="_blank" style="width: 100px; display: block;" class="btn btn-outline-secondary fw-semibold rounded-0 btn-sm" id="time">Waiting</a></td>
                {% else %}
                <td class="btn-rsch text-end"><a href="#" onclick="reschadule('{{y.tanggal}}','{{y.room.get_time_display}}','{{y.id}}')" style="width: 100px;" class="btn btn-outline-secondary fw-semibold rounded-0 btn-sm" data-bs-toggle="modal" data-bs-target="#exampleModal">Reschadule</a></td>
                {% endif %}
            </tr>
            {% endfor %}
          </tbody>
        </table>
        <div class="d-grid"><a href="{% url 'kelas:pertemuan' %}" class="btn btn-secondary btn-sm rounded-0">Lihat Semua</a></div>
      </div>
    </div>
    <div class="col-md-12 col-lg-6 mt-4">
        <div class="container shadow-sm rounded bg-white p-3" style="height: 450px;">
          <p class="h3 fw-semibold my-2">Terlaksana</p>
          <table class="table  table-hover">
            <thead>
              <tr>
                <th scope="col">Tanggal</th>
                <th scope="col">Score</th>
                <th scope="col">Feedback</th>
              </tr>
            </thead>
            <tbody>
              {% for y in done %}
              <tr style="height: 50px;">
                <td>{{y.tanggal|date:"d M"}}</td>
                <td>{% if y.performance %}{{y.performance}}/10{% else %} - {% endif %}</td>
                <td>{% if y.hadir %}{{y.feedback}}{% else %}<a href="#" onclick="reschadule('{{y.tanggal}}','{{y.room.get_time_display}}','{{y.id}}')" style="width: 100px;" class="btn btn-outline-secondary fw-semibold rounded-0 btn-sm" data-bs-toggle="modal" data-bs-target="#exampleModal">Reschadule</a>{% endif %} </td>
              </tr>
              {% endfor %}
          </table>
          <div class="d-grid"><a href="{% url 'kelas:pertemuan' %}" class="btn btn-secondary btn-sm rounded-0">Lihat Semua</a></div>
        </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Reschadule</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <form action="" method="post">
        {% csrf_token %}
        <input type="hidden" name="id" id="id">
      <div class="modal-body">
          <div class="d-flex justify-content-center h4">
            <span id="title" class="btn btn-outline-secondary rounded-0" style="width: 300px;"></span>
            <i class="fas fa-arrow-right mx-3 align-self-center"></i>
            <input type="date" name="date" id="date" style="width: 300px;" class="form-control rounded-0">
          </div>
          <div class="d-flex justify-content-center h4">
            <span id="jam" class="btn btn-outline-secondary rounded-0" style="width: 300px;"></span>
            <i class="fas fa-arrow-right mx-3 align-self-center"></i>
            <select class="form-select form-select-sm rounded-0" name="time" style="width: 300px;">
              <option selected>Pilih Jam</option>
              <option value="0">07:30</option>
              <option value="1">09:00</option>
              <option value="2">10:30</option>
              <option value="3">13:00</option>
              <option value="4">14:30</option>
              <option value="5">16:00</option>
              <option value="6">18:30</option>
              <option value="7">20:00</option>
            </select>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-outline-secondary rounded-0" data-bs-dismiss="modal">Tutup</button>
          <button type="submit" class="btn btn-secondary rounded-0">Simpan</button>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock content %}
{% block script %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
const title = document.getElementById("title")
const jam   = document.getElementById("jam")
const id  = document.getElementById("id")
function reschadule(titles, jams, ids){
  title.innerHTML = titles
  jam.innerHTML   = jams
  id.value        = ids
}
</script>
<script>
var time              = document.getElementById("time");
var countdownElement  = document.getElementById("gettime");
function updateCountdown() {
    var now = new Date();

    var initialTime = countdownElement.innerText.split(":");
    var targetHours = parseInt(initialTime[0]);
    var targetMinutes = parseInt(initialTime[1]);
    var targetTime = new Date();
    targetTime.setHours(targetHours, targetMinutes-3, 0, 0);

    var timeDiff = targetTime - now;

    if (timeDiff <= 0) {
        time.innerHTML = 'Buka Zoom';
        time.classList.remove("disabled")
    } else {
        var hours = Math.floor(timeDiff / (1000 * 60 * 60));
        var minutes = Math.floor((timeDiff % (1000 * 60 * 60)) / (1000 * 60));
        var seconds = Math.floor((timeDiff % (1000 * 60)) / 1000);

        time.innerHTML = hours + 'h ' + minutes + 'm ' + seconds + 's';
    }
}
setInterval(updateCountdown, 1000);
</script>
{% endblock script %}

templates/kelas/jadwal.html
{% extends 'dashboard.html' %}
{% load custom_tags %}
{% load static %}
{% block head %}
{% endblock head %}
{% block css %}{% endblock css %}
{% block title %}Jadwal{% endblock %}
{% block content %}
<div class="content">
  <div class="bg-white rounded shadow-sm">
    <div class="container p-3">
      <div class="row">
        <div class="col-6 col-md-3">
          <div class="display-6">Level</div>
          <div class="h4 fw-light">{{user.level.name}}<i class="ms-1 fa-regular fa-thumbs-up"></i></div>
        </div>
        <div class="col-6 col-md-3">
          <div class="display-6">Performa</div>
          <div class="h4 fw-light">30%</div>
        </div>
        <div class="col-6 col-md-3">
          <div class="display-6">Pertemuan</div>
          <div class="h5 fw-light">{{meeting.meetremain}} <span class="fw-lighter">dari</span> {{meeting.accountlevel.meeting}} Pertemuan</div>
        </div>
        <div class="col-6 col-md-3">
          <div class="display-6">Berakhir</div>
          <div class="h4 fw-light">{{meeting.end|date:"d M Y"}}</div>
        </div>
      </div>
    </div>
  </div>
  <div class="container shadow-sm mt-4 rounded bg-white p-2">
    <div class="container">
      {% if meeting.room %}
      <div class="display-6 ms-3">Jadwal saya</div>
      {% endif %}
      {% if not meeting.room %}
      <div class="display-6 ms-3">Pilih Jadwal</div>
      <hr>
      <div class="row fw-semibold">
        <div class="col-2 text-center">Mentor</div>
        <div class="col-2 text-center">Hari</div>
        <div class="col-2 text-center">Jam</div>
        <div class="col-2 text-center">Kuota</div>
        <div class="col-2 text-center">mulai</div>
        <div class="col-2 text-center">daftar</div>
      </div>
      <hr>
      {% for mentor in mentor %}
      <div class="row fw-semibold">
        <div class="col-2" style="margin-bottom: -8px;">
          <div class="d-flex justify-content-center btn" data-bs-toggle="collapse"
            data-bs-target="#mentor{{mentor.id}}" aria-expanded="false" aria-controls="mentor{{mentor.id}}">
            <div class="me-3">
              <img style="width: 40px; height: 40px; border-radius: 50%; object-fit: cover;"
                src="/media/{% if mentor.user.photo %}{{ mentor.user.photo }}{% else %}/profile/image{% random_int 1 24 %}.jpg{% endif %}"
                alt="">
            </div>
            <p class="mt-2 text-dark fw-bold">{{mentor.user.user.first_name}} {{mentor.user.user.last_name}} <i class="ms-2 fas fa-caret-down"></i></p>
          </div>
        </div>
        <div class="col-2 text-center align-self-center">{{mentor.get_jadwal_display}}</div>
        <div class="col-2 text-center align-self-center">
          <div class="btn btn-sm btn-outline-light text-muted fw-bold">{{mentor.get_time_display}}</div>
        </div>
        <div class="col-2 text-center align-self-center">{{mentor.peserta}}/{{mentor.program.siswa}}</div>
        <div class="col-2 text-center align-self-center">{% if mentor.mulai %}{{mentor.mulai|date:"d M Y"}}{%else%}Belum dimulai{%endif%}</div>
        <div class="col-2 text-center align-self-center">
          <form action="" method="post">
            {% csrf_token %}
            <input type="hidden" name="tipe" value="regular">
            <input type="hidden" name="id" value="{{ mentor.id }}">
            <button type="submit" class="btn btn-primary rounded-0">daftar</button>
          </form>
        </div>
        <div class="container collapse multi-collapse" id="mentor{{mentor.id}}">
          <div class="d-flex justify-content-between m-4 bg-light p-2 rounded-4">
            <div class=" d-flex ">
              <img style="width: 150px; height: 150px; border-radius: 10px; object-fit: cover;" src="/media/{% if mentor.user.photo %}{{ mentor.user.photo }}{% else %}/profile/image{% random_int 1 24 %}.jpg{% endif %}" alt="">
              <div class="ms-2 d-flex flex-column justify-content-between">
                <div>
                  <h5>{{mentor.user.user.first_name}} {{mentor.user.user.last_name}} </h5>
                  <p>
                  <div class="btn btn-sm btn-primary">{{mentor.teacher.mastered.name}}</div> <br>{{mentor.teacher.desc}}</p>
                  <i class="fas fa-star text-warning me-2"></i>4.8
                </div>
              </div>
            </div>
            <div class="align-self-center">
              <div class="btn text-primary btn-sm rounded-0 me-3"><i class="far fa-message h3"></i></div>
              <div class="btn text-primary btn-sm rounded-0"><i class="far fa-user h3"></i></div>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
      {% endif %}

      {% if private %}
      <hr>
      <div class="row fw-semibold">
        <div class="col-3 text-center">Mentor</div>
        <div class="col-4 text-center">Hari</div>
        <div class="col-2 text-center">Jam</div>
        <div class="col-2 text-center">daftar</div>
      </div>
      <hr>
      {% for p in private %}
      <div class="row fw-semibold">
        <!-- mentor -->
        <div class="col-3" style="margin-bottom: -8px;">
          <div class="d-flex justify-content-center btn" data-bs-toggle="collapse"
            data-bs-target="#mentor{{p.id}}" aria-expanded="false" aria-controls="mentor{{p.id}}">
            <div class="me-3">
              <img style="width: 40px; height: 40px; border-radius: 50%; object-fit: cover;"
                src="http://{{ request.get_host }}/media/{{p.mentor.photo}}"
                alt="">
            </div>
            <p class="mt-2 text-dark fw-bold">{{p.mentor.user.first_name}} {{p.mentor.user.last_name}}</p>
          </div>
        </div>
        <!-- jam -->
        <div class="col-4 text-center align-self-center">
          {% for x in p.room.all %}
            <div class="btn btn-sm btn-outline-light text-muted fw-bold">
              {{x.get_day_display}}
            </div>
            {% endfor %}
        </div>
        <div class="col-2 text-center align-self-center">{{p.room.all.0.time|date:"G:i"}}</div>
        <div class="col-2 text-center align-self-center">
          <form action="" method="post">
            {% csrf_token %}
            <input type="hidden" name="tipe" value="private">
            <input type="hidden" name="id" value="{{ p.id }}">
            <button type="submit" class="btn btn-primary rounded-0">daftar</button>
          </form>
        </div>
        <div class="container collapse multi-collapse" id="mentor{{p.id}}">
          <div class="d-flex justify-content-between m-4 bg-light p-2 rounded-4">
            <div class=" d-flex ">
              <img style="width: 150px; height: 150px; border-radius: 10px; object-fit: cover;"
                src="http://{{ request.get_host }}/media/{{p.mentor.photo}}"
                alt="">
              <div class="ms-2 d-flex flex-column justify-content-between">
                <div>
                  <h5>Muhammad Zakaria</h5>
                  <p>
                  <div class="btn btn-sm btn-primary">Intermediate</div> <br>Grammar</p>
                  <i class="fas fa-star text-warning me-2"></i>4.8
                </div>
              </div>
            </div>
            <div class="align-self-center">
              <div class="btn text-primary btn-sm rounded-0 me-3"><i class="far fa-message h3"></i></div>
              <div class="btn text-primary btn-sm rounded-0"><i class="far fa-user h3"></i></div>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
      {% endif %}
      <hr>
    </div>
  </div>
</div>
{% endblock content %}
{% block script %}
{% endblock script %}

templates/kelas/thank.html
{% extends 'dashboard.html' %}
{% load static %}
{% block head %}
{% endblock head %}
{% block css %}{% endblock css %}
{% block title %}Terima kasih{% endblock %}
{% block content %}
<div class="content d-flex justify-content-center">
    <div class="my-5 text-center"><h3>Terima kasih</h3><a href="{% url 'home' %}" class="btn btn-primary">Kembali ke halaman awal</a></div>
</div>
{% endblock content %}
{% block script %}
{% endblock script %}